export const initialState = {
    defaultTask:{
        id:'0',
        name:'Do the dashboard css fixes',
        assignee:'Jonh Doe',
        progress:'25%', 
        dueDate:'2020-10-07',
    },
    taskCount:13,
    statusList:[
        {id:'s1',name:'To Do',index:'1',tasks:[
            {
                id:'1',
                name:'Task 1 for ToDo section',
                assignee:'Choir Dior',
                progress:'25%',
                status_id:'s1',
                index_pos:'0',
                dueDate:'2020-12-07',
            },
            {
                id:'2',
                name:'Task 2 for ToDo section',
                assignee:'Daughty Sharma',
                progress:'50%',
                status_id:'s2',
                index_pos:'1',
                dueDate:'2020-12-07',
            },
            {
                id:'3',
                name:'Due Date Shots',
                assignee:'Samie Joe',
                progress:'25%',
                status_id:'s3',
                index_pos:'2',
                dueDate:'2020-08-10',
            },
            {
                id:'4',
                name:'Task 4 for ToDo section',
                assignee:'Alissa Parker',
                progress:'90%',
                status_id:'s4',
                index_pos:'3',
                dueDate:'2020-08-30',
            },
           
    
        ],},
        {id:'s2',name:'In Progress',index:'2',tasks:[
            {
                id:'5',
                name:'Task 1 In Progress section',
                assignee:'Choir Dior',
                progress:'25%',
                status_id:'s1',
                index_pos:'0',
                dueDate:'2020-08-30',
            },
            {
                id:'6',
                name:'Task 2 In Progress section',
                assignee:'Daughty Sharma',
                progress:'50%',
                status_id:'s2',
                index_pos:'1',
                dueDate:'2020-08-30',
            },
            {
                id:'7',
                name:'Task 3 In Progress section',
                assignee:'Samie Joe',
                progress:'25%',
                status_id:'s3',
                index_pos:'2',
                dueDate:'2020-08-30',
            },
          
        ],},
        {id:'s3',name:'On Hold',index:'3',tasks:[
            {
                id:'8',
                name:'Task 1 On Hold section',
                assignee:'Choir Dior',
                progress:'25%',
                status_id:'s1',
                index_pos:'0',
                dueDate:'2020-08-30',
            },
            {
                id:'9',
                name:'Task 2 On Hold section',
                assignee:'Daughty Sharma',
                progress:'50%',
                status_id:'s2',
                index_pos:'1',
                dueDate:'2020-08-30',
            },
            {
                id:'10',
                name:'Task 3 On Hold section',
                assignee:'Samie Joe',
                progress:'25%',
                status_id:'s3',
                index_pos:'2',
                dueDate:'2020-08-30',
            },
           
        
        ],},
        {id:'s4',name:'Done',index:'4',tasks:[
            {
                id:'11',
                name:'Task 1 Done section',
                assignee:'Choir Dior',
                progress:'25%',
                status_id:'s1',
                dueDate:'2020-08-30',
            },
            {
                id:'12',
                name:'Task 2Done section',
                assignee:'Daughty Sharma',
                progress:'50%',
                status_id:'s2',
                index_pos:'1',
                dueDate:'2020-08-30',
            },
            {
                id:'13',
                name:'Task 3Done section',
                assignee:'Samie Joe',
                progress:'25%',
                status_id:'s3',
                index_pos:'2',
                dueDate:'2020-08-30',
            },
        ],},
    ]  
};